import = ["~/.config/alacritty/os-settings.toml"]

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[window]
opacity = 0.7
resize_increments = true
startup_mode = "Maximized"

[window.padding]
x = 16
y = 16

[colors]
transparent_background_colors = true
