tap "scalacenter/bloop", trusted: true
tap "railwaycat/emacsmacport", trusted: true
tap "hashicorp/tap", trusted: true
tap "Virtuslab/scala-cli", trusted: true
tap "coursier/formulas", trusted: true
cask "ghostty"
cask "font-source-code-pro"
cask "font-fira-code"
cask "zed"
cask "visual-studio-code"
cask "obsidian"
cask "tomatobar"
cask "rancher"
brew "peco"
brew "git"
brew "tig"
brew "jq"
brew "gh"
brew "ghq"
brew "tmux"
brew "bat"
brew "wget"
brew "asdf"
brew "grpcurl"
brew "scalacenter/bloop/bloop"
brew "coursier/formulas/coursier" # TODO asdfから移行する
brew "kubectl"
brew "kubectx"
brew "pyenv"
brew "emacs-mac", args: ["with-modern-icon", "with-imagemagick"]
brew "stack"
brew "markdown"
brew "rust-analyzer"
brew "mysql-client@8.0"
brew "hashicorp/tap/vault"
brew "aws2-wrap"
brew "llvm" # for Scala Native
brew "bdw-gc" # for Scala Native
brew "the_silver_searcher"
brew "zig"
brew "kafka"
brew "ansible"
brew "scala-cli"
brew "sbcl"
brew "argocd"
