#!/bin/bash
set -euo

echo "profile=$AWS_PROFILE"
ACCOUNT=$(aws sts get-caller-identity --query 'Account' --output text)
REGION=$(aws configure get region --profile $AWS_PROFILE)
aws ecr get-login-password --profile $AWS_PROFILE --region ap-northeast-1 | docker login --username AWS --password-stdin "https://$ACCOUNT.dkr.ecr.$REGION.amazonaws.com"